### ISSUE TITLE
Will there be support for Epson Ethernet versions?

### ISSUE THREAD

**Issue by MrNekoShin** [seokju-na/react-thermal-printer#27]
EPSON TM-T82 doesn't have serial ports and is connected to the router which is accessible over Local IP. Will there be support for these type of thermal printers

**Comment by seokju-na** [comment]
Hi.
`react-thermal-printer` does not provide a method to communicate with devices but focuses on creating data using React.
If you are using nodejs, you can send print data to local IP using the `net` module.

```tsx
import { render, Printer, Text, Cut } from 'react-thermal-printer';
import { connect } from 'net';

const data = await render(
  <Printer type="epson" width={42}>
    <Text>Hello World</Text>
    <Cut />
  </Printer>
);

const conn = connect({
  host: '192.168.0.99',
  port: 9100,
  timeout: 3_000,
});
conn.write(Buffer.from(data), () => {
  conn.destroy();
});
conn.on('error', ...);
conn.on('timeout', ...);
```

**Comment by MrNekoShin** [comment]
I see, Thanks for the help! :)
