### ISSUE TITLE
Cyrillic alphabet is printed incorrectly, is there any options?

### ISSUE THREAD

**Issue by SyrgakRavshanbekUulu** [seokju-na/react-thermal-printer#28]

**Comment by seokju-na** [comment]
Hello 👋
You can specific print language by passing `characterSet` prop on `<Printer />` component.
e.g.
```tsx
import { render, Printer, Text, Cut } from 'react-thermal-printer';

const data = await render(
  <Printer type="epson" width={42} characterSet="pc855_cyrillic">
    <Text>Hello World</Text>
    <Cut />
  </Printer>
);
```

Alos you can find all supported character sets in [here](https://github.com/seokju-na/react-thermal-printer/blob/main/packages/printer/src/commands/characterSet.ts#L5.).

**Comment by SyrgakRavshanbekUulu** [comment]
Thank you!
