### ISSUE TITLE
Can you extract the core (non-react) part of this module and publish as a separate package?

### ISSUE THREAD

**Issue by vajahath** [seokju-na/react-thermal-printer#31]
Great work!
Can you extract the core (non-react) part of this module and publish as a separate package?
You can reuse that core package in the react-thermal-printer module as well.

**Motive:**
I was searching for a thermal printer implementation to play around with pure JS and once settled, use it in Angular. So If you could extract out the core (non-react) part and publish as a new standalone package, that would be very helpful for the community.

**Comment by seokju-na** [comment]
Hello 👋
Core part is already separated so you can use it. See [@react-thermal-printer/printer](https://www.npmjs.com/package/@react-thermal-printer/printer).

**Comment by vajahath** [comment]
Thanks!
If you could add a quick readme with some examples as well, that would be very nice. Otherwise we have to reverse engineer the code to understand the usage.

**Comment by seokju-na** [comment]
react-thermal-printer (as the name says) is a library for react. We are not considering using it as a standalone or using it in other frameworks.

**Comment by vajahath** [comment]
Thanks for the update.
