### ISSUE TITLE
Printing via Bluetooth


### ISSUE THREAD

**Issue by Hassan-jr** [seokju-na/react-thermal-printer#43]
Does this package support printing via Bluetooth and if yes please share an example.

**Comment by Hassan-jr** [comment]
@seokju-na Please respond to this.

**Comment by seokju-na** [comment]
Have you tried [Web Bluetooth API](https://developer.chrome.com/articles/bluetooth/#request)? If the interface accepts Uint8Array, printing will available.
Didn't test but you can try the code below. (or you can use bluetooth module works in [Node.js](https://www.npmjs.com/search?q=bluetooth))

```javascript
import { Printer, Text } from 'react-thermal-printer';

const device = await navigator.bluetooth({ filters: [{ name: 'Printer' }] });
const server = await device.gatt.connect();
const service = await server.getPrimaryService('printer_service');
const characteristic = await service.getCharacteristic('printer_write_characteristic');

const data = await render(
  <Printer type="epson">
    <Text>Hello World</Text>
  </Printer>
);
await characteristic.writeValue(data.buffer);
```

**Comment by Hassan-jr** [comment]
@seokju-na Thanks for the response... Let me try that.

**Comment by AlirezaBs** [comment]
@seokju-na @hempun10 @Hassan-jr 
Hi, have anybody tried the bluetooth api?
