### ISSUE TITLE
Disable floyd-steinberg  option for print image 

### ISSUE THREAD

**Issue by mengheangrat** [seokju-na/react-thermal-printer#49]
Is it posible to disable floyd-steinberg method for printing image?
- current I'm using this library to print the whole receipt because mot of printer does not support Khmer Unicode.
- so printing result with text image is not smooth

**Comment by seokju-na** [comment]
Good comment.
We can add `transform`(inject dithering algorithm) props into `<Image />` component that can be applied when converting the image to raster. Or pass nothing to disable dithering algorithm.
We will improve it in the next version.
