### ISSUE TITLE
Partial Cut Discussion

### ISSUE THREAD

**Issue by jerodfritz** [seokju-na/react-thermal-printer#57]
We have an issue where the paper is falling to the floor after a <Cut />.  It would be nice to be able to specify a partial cut.  Either as a prop on the Cut component or a new component CutPartial.  This could be implemented by adjusting the m parameter on the printer.cut() call.  Maybe allowing the m parameter to be passed as a parameter from the Cut component.  Thoughts?

**Comment by seokju-na** [comment]
This is important. Thanks for reporting this issue.
Partial cut is supported starting from version 0.17.0 (https://github.com/seokju-na/react-thermal-printer/pull/61)

```tsx
import { Printer, Text, Cut, render } from 'react-thermal-printer';

const data = await render(
  <Printer type="epson">
    <Text>Hello World</Text>
    <Cut partial={true} />
  </Printer>
);
```
