### ISSUE TITLE
can i render three aligns like this

### ISSUE THREAD

**Issue by TraFost** [seokju-na/react-thermal-printer#68]
<Row
    left={
    <Text>
      <Text align="left">메뉴명</Text>
      <Text align="center">수량</Text>
    </Text>
    }
    right="가격"
  />

**Comment by TraFost** [comment]
![Capture](https://github.com/seokju-na/react-thermal-printer/assets/93178373/9f61a968-2efb-4083-b95a-30b2c36e8f55)

**Comment by TraFost** [comment]
![image](https://github.com/seokju-na/react-thermal-printer/assets/93178373/235f9f12-076c-4e90-b573-dec5b054b95c)

if anyone got this error, please expand the width of the printer component. ty

**Comment by Walidnurudin** [comment]
Im implement same code like you, i got error "Invalid count value: -1".
please check width size ...

I hope this help.
