### ISSUE TITLE
Just pointing out an alternative method

### ISSUE THREAD

**Issue by vajahath** [seokju-na/react-thermal-printer#70]
First, thank for your incredible work ⭐ 

I could keep this myself without bothering you. But seeing #64 and many others, I thought I could just open this issue.

I made a fork: https://github.com/vajahath/image-thermal-printer

What it basically does is convert the "thing to print" into an image (or `HTMLCanvasElemet`) and use the https://github.com/seokju-na/react-thermal-printer/blob/main/packages/printer/src/commands/image.ts image command on it.

So far, it is working nice-ish (some tweaks needed here and there)

I converted my div into canvas (https://www.npmjs.com/package/html-to-image#toCanvas). Then printed it using the above command. This gave me unlimited customization.

(the printer I'm using is very old and of low quality - hence some lines segments are lost)
![PXL_20240224_181001863 MP](https://github.com/seokju-na/react-thermal-printer/assets/12165822/a6c9f8fd-7f95-46d5-89b4-3f474e71a0f3)

Because the printers are generally having low resolution, serif typeface may not be a good choice. I prefer sans serif typeface. Roboto is a good choice. (Noto as well). Any font that claims to work well in low-res could be a good choice.

Some advantages I found:
- Alignment: This is a solved problem in html. With now we having the [container-queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries), we can design a div the way we want.
- Tables: html tables adjust themselves
- Responsive: Thermal printer comes in many width - 2 inch (my case), 3 inch. With the right css you can target any number of widths.
- Tiny and simplified code (mainly image manipulation is only required)
- Framework agnostic. 

Cons:
- Need to fiddle around the printer dpi (mine is `200`) and possible print widths.

---
This issue was to inform you an alternative method. Feel free to close this issue whenever you wish.

**Comment by vajahath** [comment]
Also the https://en.wikipedia.org/wiki/Atkinson_dithering claims to provide better contrast than Floyd–Steinberg. Its integration may also provide slightly better results - just pointing out.

**Comment by m90khan** [comment]
This is good. I do not have any thermal printers around at the moment.
so that means it can work with any thermal printer brand. It does not have to be Epson or Star. ?

**Comment by vajahath** [comment]
Thank you.
Afaik, the printer itself doesn't have to be from Epson or star. Most printers I encountered (a fairly small number) do follow the Epson/star protocol. So you should be good to go. 🤞

**Comment by m90khan** [comment]
Thanks for your reply. helpful :)
