### ISSUE TITLE
Can you export this as a type like PrinterType?

### ISSUE THREAD

**Issue by jay-babu** [seokju-na/react-thermal-printer#71]
https://github.com/seokju-na/react-thermal-printer/blob/65b23afdb255a139eafa03a7dee0fcf95bd04fe1/packages/react-thermal-printer/src/components/Printer.tsx#L31

**Comment by seokju-na** [comment]
You can use `ComponentProps` type from `react` module.

```tsx
import type { ComponentProps }  from 'react';
import type { Printer } from 'react-thermal-printer';

type PrinterProps = ComponentProps<typeof Printer>;
```
