### ISSUE TITLE
help with electron js and react js enviroment ASAP !important

### ISSUE THREAD

**Issue by argjendhaxhijaj** [seokju-na/react-thermal-printer#75]
I need to set this library in order to work with electron and react js environment.

I understand that I need to use https://serialport.io/docs/guide-installation but the question is how can I make the connection with react js is that possible please help me I need it ASAP.

**Comment by argjendhaxhijaj** [comment]
@seokju-na

**Comment by seokju-na** [comment]
Yes, It is possible to use React.js in nodejs unless you use the react-dom API.
