### ISSUE TITLE
Unable to use custom Components as the Printer content

### ISSUE THREAD

**Issue by Toscanah** [seokju-na/react-thermal-printer#79]
I’m trying to create reusable components for common parts of my receipts, here's an example of what I currently have:

```tsx
import { Text } from "react-thermal-printer";

const Header = () => (
  <>
    <Text align="center">Some text 1</Text>
    <Text align="center">Some text 2</Text>
    <Text align="center">Some text 3</Text>
    <Text align="center">Some text 4</Text>
  </>
);

export default Header;
``` 

So I try to use this `Header` component in my receipt printing logic, like this:

```tsx
import { Printer } from "react-thermal-printer";
import Takeaway from "./Takeaway";

export default function Printing() {
  async function print() {
    const receipt = (
      <Printer type="epson">
        <Takeaway />
      </Printer>
    );

    const data: Uint8Array = await render(receipt);
    const port = await (window as any).navigator.serial.requestPort();
    await port.open({ baudRate: 19200 });

    console.log(data);

    const writer = port.writable?.getWriter();

    if (writer != null) {
      await writer.write(data);
      writer.releaseLock();
    }
  }

  return (
    <div className="flex gap-4">
      <Button onClick={print}>Print/Button>
    </div>
  );
}
```

However, the printer doesn’t print anything. When checking the console, it shows the `Uint8Array` output as `[27, 64]`, which seems to be just some default commands for the printer. If instead, I put those `<Text>` Components directly inside the Printer, everything works as expected.

Am I missing something? Can I even do this? Using Component to encapsulate common parts of my receipts?

Looking at the source code it should work, but it doesn't. Any fix is appreciated, thanks.

**Comment by seokju-na** [comment]
This is currently known issue with custom components not being supported. 

Try renderer instead of components.

```tsx
import { Printer, Text } from "react-thermal-printer";

function renderTakeaway() {
  return (
    <>
      <Text>Hello</Text>
    </>
  );
}

export default function Printing() {
  async function print() {
    const receipt = (
      <Printer type="epson">
        {renderTakeaway()}
      </Printer>
    );
    // ...
  }
  // ...
}
```

**Comment by Toscanah** [comment]
> This is currently known issue with custom components not being supported.
> 
> Try renderer instead of components.
> 
> ```tsx
> import { Printer, Text } from "react-thermal-printer";
> 
> function renderTakeaway() {
>   return (
>     <>
>       <Text>Hello</Text>
>     </>
>   );
> }
> 
> export default function Printing() {
>   async function print() {
>     const receipt = (
>       <Printer type="epson">
>         {renderTakeaway()}
>       </Printer>
>     );
>     // ...
>   }
>   // ...
> }
> ```

This works, thank you so much.

**Comment by seokju-na** [comment]
Improved to support Custom Component starting from version 0.19.0. (#80)

Please try it and give feedback. Thank you.
